AutomationDashboard.Web/Controllers/BuildController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AutomationDashboard.Data;
using AutomationDashboard.Model.Models;

namespace AutomationDashboard.Web.Controllers
{
    public class BuildController : Controller
    {
        private AutomationDashboardDbContext db = new AutomationDashboardDbContext();

        // GET: Build
        public async Task<ActionResult> Index()
        {
            var builds = db.Builds.Include(b => b.BuildDetails).Include(b => b.SubProject);
            return View(await builds.ToListAsync());
        }

        // GET: Build/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Build build = await db.Builds.FindAsync(id);
            if (build == null)
            {
                return HttpNotFound();
            }
            return View(build);
        }

        // GET: Build/Create
        public ActionResult Create()
        {
            ViewBag.Id = new SelectList(db.BuildDetails, "Id", "Id");
            ViewBag.SubProjectId = new SelectList(db.SubProjects, "Id", "FullName");
            return View();
        }

        // POST: Build/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,BuildId,Number,Status,State,Pinned,WebUrl,Count,StartDate,FinishDate,Duration,SubProjectId")] Build build)
        {
            if (ModelState.IsValid)
            {
                db.Builds.Add(build);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.Id = new SelectList(db.BuildDetails, "Id", "Id", build.Id);
            ViewBag.SubProjectId = new SelectList(db.SubProjects, "Id", "FullName", build.SubProjectId);
            return View(build);
        }

        // GET: Build/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Build build = await db.Builds.FindAsync(id);
            if (build == null)
            {
                return HttpNotFound();
            }
            ViewBag.Id = new SelectList(db.BuildDetails, "Id", "Id", build.Id);
            ViewBag.SubProjectId = new SelectList(db.SubProjects, "Id", "FullName", build.SubProjectId);
            return View(build);
        }

        // POST: Build/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,BuildId,Number,Status,State,Pinned,WebUrl,Count,StartDate,FinishDate,Duration,SubProjectId")] Build build)
        {
            if (ModelState.IsValid)
            {
                db.Entry(build).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.Id = new SelectList(db.BuildDetails, "Id", "Id", build.Id);
            ViewBag.SubProjectId = new SelectList(db.SubProjects, "Id", "FullName", build.SubProjectId);
            return View(build);
        }

        // GET: Build/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Build build = await db.Builds.FindAsync(id);
            if (build == null)
            {
                return HttpNotFound();
            }
            return View(build);
        }

        // POST: Build/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Build build = await db.Builds.FindAsync(id);
            db.Builds.Remove(build);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AutomationDashboard.Web/Controllers/BuildDetailController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AutomationDashboard.Data;
using AutomationDashboard.Model.Models;

namespace AutomationDashboard.Web.Controllers
{
    public class BuildDetailController : Controller
    {
        private AutomationDashboardDbContext db = new AutomationDashboardDbContext();

        // GET: BuildDetail
        public async Task<ActionResult> Index()
        {
            var buildDetails = db.BuildDetails.Include(b => b.Build);
            return View(await buildDetails.ToListAsync());
        }

        // GET: BuildDetail/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BuildDetail buildDetail = await db.BuildDetails.FindAsync(id);
            if (buildDetail == null)
            {
                return HttpNotFound();
            }
            return View(buildDetail);
        }

        // GET: BuildDetail/Create
        public ActionResult Create()
        {
            ViewBag.Id = new SelectList(db.Builds, "Id", "Status");
            return View();
        }

        // POST: BuildDetail/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,Pass,Fail,NotRun,DateTime")] BuildDetail buildDetail)
        {
            if (ModelState.IsValid)
            {
                db.BuildDetails.Add(buildDetail);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.Id = new SelectList(db.Builds, "Id", "Status", buildDetail.Id);
            return View(buildDetail);
        }

        // GET: BuildDetail/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BuildDetail buildDetail = await db.BuildDetails.FindAsync(id);
            if (buildDetail == null)
            {
                return HttpNotFound();
            }
            ViewBag.Id = new SelectList(db.Builds, "Id", "Status", buildDetail.Id);
            return View(buildDetail);
        }

        // POST: BuildDetail/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Pass,Fail,NotRun,DateTime")] BuildDetail buildDetail)
        {
            if (ModelState.IsValid)
            {
                db.Entry(buildDetail).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.Id = new SelectList(db.Builds, "Id", "Status", buildDetail.Id);
            return View(buildDetail);
        }

        // GET: BuildDetail/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BuildDetail buildDetail = await db.BuildDetails.FindAsync(id);
            if (buildDetail == null)
            {
                return HttpNotFound();
            }
            return View(buildDetail);
        }

        // POST: BuildDetail/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            BuildDetail buildDetail = await db.BuildDetails.FindAsync(id);
            db.BuildDetails.Remove(buildDetail);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AutomationDashboard.Web/Controllers/ProjectController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AutomationDashboard.Data;
using AutomationDashboard.Model.Models;

namespace AutomationDashboard.Web.Controllers
{
    public class ProjectController : Controller
    {
        private AutomationDashboardDbContext db = new AutomationDashboardDbContext();

        // GET: Project
        public async Task<ActionResult> Index()
        {
            var projects = db.Projects.Include(p => p.Setting);
            return View(await projects.ToListAsync());
        }

        // GET: Project/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Project project = await db.Projects.FindAsync(id);
            if (project == null)
            {
                return HttpNotFound();
            }
            return View(project);
        }

        // GET: Project/Create
        public ActionResult Create()
        {
            ViewBag.SettingId = new SelectList(db.Settings, "Id", "Name");
            return View();
        }

        // POST: Project/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,FullName,DisplayName,UserName,Password,Activate,SettingId")] Project project)
        {
            if (ModelState.IsValid)
            {
                db.Projects.Add(project);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.SettingId = new SelectList(db.Settings, "Id", "Name", project.SettingId);
            return View(project);
        }

        // GET: Project/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Project project = await db.Projects.FindAsync(id);
            if (project == null)
            {
                return HttpNotFound();
            }
            ViewBag.SettingId = new SelectList(db.Settings, "Id", "Name", project.SettingId);
            return View(project);
        }

        // POST: Project/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,FullName,DisplayName,UserName,Password,Activate,SettingId")] Project project)
        {
            if (ModelState.IsValid)
            {
                db.Entry(project).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.SettingId = new SelectList(db.Settings, "Id", "Name", project.SettingId);
            return View(project);
        }

        // GET: Project/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Project project = await db.Projects.FindAsync(id);
            if (project == null)
            {
                return HttpNotFound();
            }
            return View(project);
        }

        // POST: Project/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Project project = await db.Projects.FindAsync(id);
            db.Projects.Remove(project);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AutomationDashboard.Web/Controllers/SettingController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AutomationDashboard.Data;
using AutomationDashboard.Model.Models;

namespace AutomationDashboard.Web.Controllers
{
    public class SettingController : Controller
    {
        private AutomationDashboardDbContext db = new AutomationDashboardDbContext();

        // GET: Setting
        public async Task<ActionResult> Index()
        {
            return View(await db.Settings.ToListAsync());
        }

        // GET: Setting/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Setting setting = await db.Settings.FindAsync(id);
            if (setting == null)
            {
                return HttpNotFound();
            }
            return View(setting);
        }

        // GET: Setting/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Setting/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,Name,Domain,UrlBuildStart,UrlBuildEnd,UrlReportStart,UrlReportEnd")] Setting setting)
        {
            if (ModelState.IsValid)
            {
                db.Settings.Add(setting);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(setting);
        }

        // GET: Setting/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Setting setting = await db.Settings.FindAsync(id);
            if (setting == null)
            {
                return HttpNotFound();
            }
            return View(setting);
        }

        // POST: Setting/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Name,Domain,UrlBuildStart,UrlBuildEnd,UrlReportStart,UrlReportEnd")] Setting setting)
        {
            if (ModelState.IsValid)
            {
                db.Entry(setting).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(setting);
        }

        // GET: Setting/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Setting setting = await db.Settings.FindAsync(id);
            if (setting == null)
            {
                return HttpNotFound();
            }
            return View(setting);
        }

        // POST: Setting/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Setting setting = await db.Settings.FindAsync(id);
            db.Settings.Remove(setting);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AutomationDashboard.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="@Url.Content("~/Content/images/favicon.ico")" />

    <title>Niteco Automation Dashboard</title>

    <!-- Bootstrap -->
    <link href="~/Content/vendors/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="~/Content/vendors/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <!-- NProgress -->
    <link href="~/Content/vendors/nprogress/nprogress.css" rel="stylesheet">
    <!-- Custom Theme Style -->
    <link href="~/Content/build/css/custom.css" rel="stylesheet">


</head>
<body class="nav-md">
    <div class="container body">
        <div class="main_container">
            <div class="col-md-3 left_col menu_fixed">
                <div class="left_col scroll-view">
                    <div class="navbar nav_title" style="border: 0;">
                        <a href="/" class="site_title"><i class="fa fa-bar-chart-o"></i> <span>Automation Tools</span></a>
                    </div>
                    <div class="clearfix"></div>
                    <br />

                    <!-- sidebar menu -->
                    @{ Html.RenderAction("SidebarMenu", "Home"); }
                    <!-- sidebar menu -->
                    <!-- menu footer buttons -->
                    <div class="sidebar-footer hidden-small">
                    </div>
                    <!-- menu footer buttons -->

                </div>
            </div>

            <!-- top navigation -->
            <div class="top_nav">
                <div class="nav_menu">
                    <nav>
                        <div class="nav toggle">
                            <a id="menu_toggle"><i class="fa fa-bars"></i></a>
                        </div>
                    </nav>
                </div>
            </div>
            <!-- top navigation -->
            <!-- page content -->
            @RenderBody()
            <!-- page content -->
            <!-- footer content -->
            <footer>
                <div class="pull-right">
                    © Copyright 2018 <a href="https://niteco.com"> Niteco</a>
                </div>
                <div class="clearfix"></div>
            </footer>
            <!-- footer content -->
        </div>
    </div>


    <!-- jQuery -->
    <script src="~/Content/vendors/jquery/dist/jquery.min.js"></script>
    <!-- Bootstrap -->
    <script src="~/Content/vendors/bootstrap/dist/js/bootstrap.min.js"></script>
    <!-- FastClick -->
    <script src="~/Content/vendors/fastclick/lib/fastclick.js"></script>
    <!-- NProgress -->
    <script src="~/Content/vendors/nprogress/nprogress.js"></script>
    <!-- Chart.js -->
    <script src="~/Content/production/js/chartjs/Chart.min.272.js"></script>
    <!-- Custom Theme Scripts -->
    <script src="~/Content/build/js/custom.js"></script>
    

</body>
</html>

AutomationDashboard.Web/Views/Shared/_LayoutHomeSetting.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="@Url.Content("~/Content/images/favicon.ico")" />

    <title>Niteco Automation Dashboard</title>

    <!-- Bootstrap -->
    <link href="~/Content/vendors/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="~/Content/vendors/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <!-- NProgress -->
    <link href="~/Content/vendors/nprogress/nprogress.css" rel="stylesheet">
    <!-- Custom Theme Style -->
    <link href="~/Content/build/css/custom.css" rel="stylesheet">

    <!-- bootstrap-daterangepicker -->
    <link href="~/Content/vendors/bootstrap-daterangepicker/daterangepicker.css" rel="stylesheet">
    <!-- bootstrap-datetimepicker -->
    <link href="~/Content/vendors/bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.css" rel="stylesheet">


</head>
<body>
    <div class="container body">
        <div class="">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2><i class="fa fa-pie-chart"></i><a href="@Url.Action("Index", "Home", new { })">Automation Tools</a></h2>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">
                        <div class="" role="tabpanel" data-example-id="togglable-tabs">
                            <ul id="myTab" class="nav nav-tabs bar_tabs" role="tablist">
                                <li role="presentation" class="">
                                    <a href="@Url.Action("Index", "Setting", new { })" role="tab" aria-expanded="false">Settings</a>
                                </li>
                                <li role="presentation" class="">
                                    <a href="@Url.Action("Index", "Project", new { })" role="tab" aria-expanded="false">Projects</a>
                                </li>
                                <li class="">
                                    <a href="@Url.Action("Index", "SubProject", new { })" role="tab" aria-expanded="false">SubProjects</a>
                                </li>
                                <li role="presentation" class="">
                                    <a href="@Url.Action("Index", "Build", new { })" role="tab" aria-expanded="false">Builds</a>
                                </li>
                                <li role="presentation" class="">
                                    <a href="@Url.Action("Index", "BuildDetail", new { })" role="tab" aria-expanded="false">Build Details</a>
                                </li>
                                <li role="presentation" class="">
                                    <a href="@Url.Action("CronSetting", "Home", new { })" role="tab" aria-expanded="false">Crons</a>
                                </li>
                            </ul>
                            <div id="myTabContent" class="tab-content">
                                @RenderBody()
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <!-- jQuery -->
    <script src="~/Content/vendors/jquery/dist/jquery.min.js"></script>
    <!-- Bootstrap -->
    <script src="~/Content/vendors/bootstrap/dist/js/bootstrap.min.js"></script>
    <!-- FastClick -->
    <script src="~/Content/vendors/fastclick/lib/fastclick.js"></script>
    <!-- NProgress -->
    <script src="~/Content/vendors/nprogress/nprogress.js"></script>
    <!-- Chart.js -->
    <script src="~/Content/production/js/chartjs/Chart.min.272.js"></script>
    <!-- Custom Theme Scripts -->
    <script src="~/Content/build/js/custom.js"></script>

    <!-- bootstrap-daterangepicker -->
    <script src="~/Content/vendors/moment/min/moment.min.js"></script>
    <script src="~/Content/vendors/bootstrap-daterangepicker/daterangepicker.js"></script>
    <!-- bootstrap-datetimepicker -->
    <script src="~/Content/vendors/bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js"></script>



</body>
</html>

AutomationDashboard.Web/Views/Shared/_SidebarMenu.cshtml
@using AutomationDashboard.Web.Models
@using AutomationDashboard.Model.Models
@model List<MenuViewModel>

@{
    Layout = null;
}

<div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
    <div class="menu_section">
        <ul class="nav side-menu">

            <li>
                <a href="/"><i class="fa fa-pie-chart"></i> Dashboard </a>
            </li>

            @foreach (MenuViewModel item in Model)
            {
                <li>
                    <a><i class="fa fa-folder-open"></i> @item.Project.DisplayName <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                        @foreach (SubProject subProject in item.SubProjects)
                        {
                            <li>@Html.ActionLink(subProject.DisplayName, "GetBuild", "Home", routeValues: new { subProjectId = subProject.Id }, htmlAttributes: new { alt = subProject.Id })</li>
                        }
                    </ul>
                </li>
            }

             <li>
                  <a href="/Setting/Index"><i class="fa fa-cog"></i> Setting <span class="fa fa-chevron-down"></span></a>
             </li>

        </ul>
    </div>

</div>